source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'pruebaFr_Example', :exclusive => true do
  pod 'pruebaFr', :path => '../'
end

target 'pruebaFr_Tests', :exclusive => true do
  pod 'pruebaFr', :path => '../'

  
end
